#!/bin/bash

big() {
  pasteit() {
  		paste <(echo "$1") <(echo "$2")
		echo "==================================================="
  }

  DATA=$( du -sh /nix/store/* | sort -h | tail -10)
  SIZE=$(echo "$DATA" | awk '{print $1}')
  PACKAGE=$(echo "$DATA" | awk '{print $2}' | cut -d'-' -f2-)

  pasteit "Size" "Package"
  pasteit "$SIZE" "$PACKAGE"
}
