#!/bin/bash
[options]
scroll_on_output = false
scroll_on_keystroke = true
audible_bell = false
mouse_autohide = false
allow_bold = false
dynamic_title = true
urgent_on_bell = true
clickable_url = true
font = Inconsolata bold 10
scrollback_lines = 10000
search_wrap = true
#icon_name = terminal

# "system", "on" or "off"
cursor_blink = system

# "block", "underline" or "ibeam"
cursor_shape = ibeam

# $BROWSER is used by default if set, with xdg-open as a fallback

# set size hints for the window
#size_hints = false

# Hide links that are no longer valid in url select overlay mode
filter_unmatched_urls = true

# emit escape sequences for extra modified keys
#modify_other_keys = false

[colors]
#foreground = #7e62b3
foreground = #cccccc
foreground_bold = #d3d3d3
#background = #1e1e1e
background = rgba(20, 20, 20, .8)

# 20% background transparency (requires a compositor)
#background = rgba(0, 0, 0, 0.8)

# if unset, will reverse foreground and background
highlight = #2f2f2f

# colors from color0 to color254 can be set
color0 = #333333
color1 = #8c4665
color2 = #287373
color3 = #7c7c99
color4 = #395573
color5 = #5e468c
color6 = #31658c
color7 = #899ca1
color8 = #3d3d3d
color9 = #bf4d80
color10 = #43a6a6
color11 = #9e9ecb
color12 = #477ab3
color13 = #7e62b3
color14 = #6096bf
color15 = #c0c0c0

[hints]
#roundness = 100.0
