# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/lib/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

# WINDOW NAME

[windowname.sh]
label=
command=xtitle -s
color=#d3d3d3
interval=persist
separator_block_width=10
separator=false

# WEATHER

[weather.sh]
command=/home/req/.scripts/weather.sh "85283"
interval=1500
color=#FFFFFF
separator_block_width=10
separator=false

# Gmail

[gmail.sh]
command=echo -e "  $(/home/req/.scripts/gmail.sh)"
interval=100
#instance=/home/req/.scripts/login.sh
color=#FF8396
markup=pango
#min_width=500
separator_block_width=10
separator=false


# MPD
[mpd_block]
label= 
color=#D3D3D3
interval=1
command=/home/req/.scripts/mpd_block
min_width=550
separator=false

# RSS Feed
#[feed]
#command=~/.scripts/feed
#label=
#color=#FF4C4C
#interval=60
#separator=false

# Volume indicator

[volume]
label=
instance=Master
interval=5
signal=10
color=#ffffff
separator=false


# Memory usage

#[memory]
#label=
#separator=false
#interval=30
#color=#D3D3D3


#[disk]
#label=
#interval=30
#color=#D3D3D3
#separator=false

# Network interface monitoring

#[iface]
#label=
#color=#009900
#interval=10
#separator=false
#command=/usr/lib/i3blocks/iface

# Calendar

[calendar.sh]
label=
command=~/.scripts/calendar.sh
color=#FF8396
markup=pango
interval=5
separator=false


# Time

[time]
label=
color=#FF8396
command=~/.scripts/time
markup=pango
interval=5
separator=false


[battery.sh]
label=
command=~/.scripts/battery.sh
interval=10
separator=false

# Welcome User

[name_block]
label=
color=#FF8396
markup=pango
command=~/.scripts/name_block
interval=once
separator=false
min_width=110
