:REVEAL_PROPERTIES:
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_REVEAL_JS_VERSION: 4
:END:

#+TITLE: Emacs Configuration File
#+DATE: <2022-01-31 Mon>
#+EXPORT_FILE_NAME: ~/org/exports/settings.html

* Functionality
** Evil
#+begin_quote
Evil is an extensible vi layer for Emacs. It emulates the main features of Vim, and provides facilities for writing custom extensions. Also see our page on EmacsWiki.
#+end_quote

*** Base
#+begin_src emacs-lisp
(use-package evil
  :ensure t
  :defer .1
  :init
  (setq evil-want-keybinding nil)
  (setq evil-want-integration t)
  (setq evil-search-module 'evil-search)
  (setq evil-ex-complete-emacs-commands nil)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (setq evil-shift-round nil)
  (setq evil-want-C-u-scroll t)
  (setq-default evil-auto-indent nil)
  (with-eval-after-load 'evil-maps
    (define-key evil-motion-state-map (kbd ":") 'evil-repeat-find-char)
    (define-key evil-motion-state-map (kbd "<SPC>") 'evil-ex)
    (define-key evil-motion-state-map (kbd "f") 'helm-find-files))
  :config
  (evil-mode))
#+end_src

*** Collection
#+begin_src emacs-lisp
(use-package evil-collection
  :after evil
  :ensure t
  :custom
  (evil-collection-setup-minibuffer t)
  :config
  (evil-collection-init))
#+end_src

** org-tempo
This lets me use '<s' to auto complete source blocks
#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src

** backup files
Get rid of emacs clutter
#+begin_src emacs-lisp
(setq make-backup-files nil)
#+end_src

** set firefox to open =.html= and =.xhtml=
Allow export to html to open in firefox
 #+begin_src emacs-lisp
 (setq org-file-apps
       '((auto-mode . emacs)
         ("\\(?:xhtml\\|html\\)\\'" . "firefox %s")))
 #+end_src

** magit
#+begin_src emacs-lisp
(use-package magit
  :ensure t)
#+end_src

** yasnippet
#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t
  :init
  (yas-global-mode 1))
#+end_src

** org-reveal
#+begin_src emacs-lisp
(use-package ox-reveal
  :ensure t)
#+end_src

** helm
#+begin_src emacs-lisp
(use-package helm
  :ensure t
  :init
  (helm-mode 1)
  :config
  (global-set-key (kbd "M-x") 'helm-M-x)
  ;;(define-key evil-ex-map "e" 'helm-find-files)
  (setq-default helm-M-x-fuzzy-match t)
  (setq helm-split-window-in-side-p t)
  (setq helm-move-to-line-cycle-in-source t))
#+end_src

** nix mode
#+begin_src emacs-lisp
(use-package nix-mode
  :ensure t
  :mode "\\.nix\\'")
#+end_src

** direnv
#+begin_src emacs-lisp
(use-package direnv
  :ensure t
  :config
  (direnv-mode))
#+end_src

** perspective

#+begin_src emacs-lisp
(use-package perspective
  :ensure t
  :bind
  (
    ("C-x C-b" . persp-list-buffers)
  )
  :config
  (persp-mode))
#+end_src

** exwm
#+begin_src emacs-lisp
(use-package exwm
  :ensure t
  :config
  (require 'exwm-config)
  (server-start)
  (setq exwm-workspace-number 1))
#+end_src

** load custom path
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.config/emacs/lisp/")
#+end_src

** flycheck
*** base
#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :config
  (add-hook 'org-mode-hook 'flycheck-mode))
#+end_src
*** flycheck-grammarly
#+begin_src emacs-lisp
(use-package flycheck-grammarly
  :ensure t
  :after flycheck
  :config
  (setq flycheck-grammarly-check-time 0.8)
  (add-to-list 'flycheck-checkers 'grammarly))
#+end_src
* UI
** remove startup screens
#+begin_src emacs-lisp
(setq inhibit-startup-screen t)
(setq inhibit-splash-screen t)
(setq inhibit-startup-message t)
#+end_src

** bars
*** General
Remove all the toolbars & scrollbars
#+begin_src emacs-lisp
(menu-bar-mode -1)
(toggle-scroll-bar -1)
(tool-bar-mode -1)
#+end_src
*** org-bars
Dependency package for org-bars
#+begin_src emacs-lisp
(use-package s
  :ensure t)
#+end_src

#+begin_src emacs-lisp
(load "org-bars")
(require 'org-bars)
(setq org-bars-extra-pixels-height 20)
(setq org-bars-with-dynamic-stars-p t)
(setq org-bars-stars '(
    :empty "*"
    :invisible "+"
    :visible "-"))

(defun org-no-ellipsis-in-headlines ()
  "Remove use of ellipsis in headlines.
See `buffer-invisibility-spec'."
  (remove-from-invisibility-spec '(outline . t))
  (add-to-invisibility-spec 'outline))

(add-hook 'org-mode-hook 'org-no-ellipsis-in-headlines)
(add-hook 'org-mode-hook #'org-bars-mode)
#+end_src

** highlight current line
#+begin_src emacs-lisp
(global-hl-line-mode t)
(set-face-background 'hl-line "#25262B")
#+end_src

** visual line mode
#+begin_src emacs-lisp
;; (global-visual-line-mode 1)
#+end_src

** all-the-icons
give me all the icons
#+begin_src emacs-lisp
(use-package all-the-icons
  :ensure t
  :config
  (set-fontset-font t 'unicode (font-spec :family "FontAwesome") nil 'append))
#+end_src

** Dashboard
Startup dashboard for a nice looking entrance
#+begin_src emacs-lisp
(use-package dashboard
  :init
  (setq dashboard-banner-logo-title "")
  (setq dashboard-center-content t)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-startup-banner "/home/req/Pictures/logos/logo.png")
  (setq dashboard-set-init-info t)
  (setq dashboard-set-footer t)
  (setq dashboard-set-navigator t)
  (setq dashboard-navigator-buttons
    `((
       (,(all-the-icons-octicon "mark-github" :height 0.9 :v-adjust 0.0)
              "Homepage"
              "Browse homepage"
              (lambda (&rest _) (browse-url "https://github.com/risolij/dotfiles")))

       (,(all-the-icons-faicon "youtube-play" :height 0.9 :v-adjust 0.0)
              "Youtube"
              "Probably watch gingergm"
              (lambda (&rest _) (browse-url "https://youtube.com")))

       (,(all-the-icons-faicon "sticky-note" :height 0.9 :v-adjust 0.0)
              "Notes"
              "Notes file"
              (lambda (&rest _) (find-file "~/org/notes.org")))

       (,(all-the-icons-octicon "gear" :height 0.9 :v-adjust 0.0)
              "Configuration"
              "Click to config Emacs"
              (lambda (&rest _) (find-file "~/org/dev/git/dotfiles/.config/emacs/settings.org"))))))
  :ensure t
  :config
  (dashboard-setup-startup-hook))
#+end_src

** themes
Let's not try to create our own theme & just use a good one that exists
#+begin_src emacs-lisp
(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold t
 doom-themes-enable-italic t)
  (load-theme 'doom-one t)
  (doom-themes-visual-bell-config)
  (doom-themes-neotree-config)
  (setq doom-themes-treemacs-theme "doom-atom")
  (doom-themes-treemacs-config)
  (doom-themes-org-config))
#+end_src

** font
*** Inconsolata
#+begin_src emacs-lisp
(set-face-attribute 'default nil :font "Inconsolata-18" )
#+end_src

*** fontawesome
#+begin_src emacs-lisp
(use-package fontawesome
  :ensure t)
#+end_src

** pretty bullets
Make org files that much better looking with font awesome icon
#+begin_src emacs-lisp
;; (use-package org-superstar
;;   :ensure t
;;   :hook (org-mode . (lambda () (org-superstar-mode 1)))
;;   :config
;;   (setq org-superstar-headline-bullets-list (fontawesome "square-caret-right"))
;;   ;;(setq org-superstar-headline-bullets-list (fontawesome "gear"))
;;   (setq org-superstar-special-todo-items t)
;;   (setq org-superstar-todo-bullet-alist
;;       '(
;;         ("TODO" "")
;;         ("NEXT" "✒")
;;         ("WAIT" "☕")
;;         ("CXLD" "✘")
;;         ("DONE" "✔")
;;        )))
#+end_src

** rainbow delimiters
So I can tell where 1 begins and 1 ends
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :ensure t
  :config
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+end_src

** writeroom
Focus mode in org files for centered text & remove all the extras
#+begin_src emacs-lisp
(use-package writeroom-mode
  :ensure t
  :hook org-mode)
#+end_src

** collapsed headers on open
#+begin_src emacs-lisp
(setq org-startup-folded t)
#+end_src

** code blocks
trying to get rid of the auto indentation when creating source blocks. Don't think this quite fixes everything.
#+begin_src emacs-lisp
(setq org-src-fontify-natively t)
(setq org-src-window-setup 'current-window)
(setq org-edit-src-content-indentation 0)
(setq org-src-strip-leading-and-trailing-blank-lines t)
(setq org-src-preserve-indentation nil)
(setq org-src-tab-acts-natively t)
#+end_src

** focus
#+begin_src emacs-lisp
(use-package focus
  :ensure t
  :hook (org-mode . (lambda () (focus-mode))))
#+end_src
