#!/bin/bash
# This script will compile or run another finishing operation on a document. I have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.
# Opens .sent filenames as sent presentations.
# Runs scripts based on extention or shebang

filepath=$(dirname $(readlink -f "$1"))
file=$(basename "$1")
base=${file%%.*}
ext=${file##*.}

echo $filepath
echo $file
echo $base
echo $ext


cd "$filepath" || exit

case "$ext" in
	ms) groff -me -ms -kejpt "$file" -T pdf > "$base".pdf ;;
	mom) groff -mom "$file" -T pdf > "$base.pdf" ;;
esac


